ENV PYTORCH_ROCM_ARCH=gfx942
ENV ROCM_PATH=/opt/rocm/                                                      
ENV CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}   
RUN conda install cmake ninja
RUN git clone -b tunable_op_torch2.0_mi300 https://github.com/ROCm/pytorch.git && cd pytorch && git apply ft.patch && conda install --file requirements.txt && bash install.sh
